name: Deploy Frontend to GCS

on:
  push:
    branches: [main]
    paths:
      - 'fe/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build Frontend
        working-directory: ./fe
        run: |
          npm install
          npm run build

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Who am I (debug)
        run: gcloud auth list && gcloud config list

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r fe/dist gs://${{ secrets.BUCKET_NAME }}
          gsutil web set -m index.html -e index.html gs://${{ secrets.BUCKET_NAME }}
          gsutil iam ch allUsers:objectViewer gs://${{ secrets.BUCKET_NAME }}
