name: Docker CI for Socially

on:
  push:
    branches: [ "main" ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
