name: Docker CI for Socially

on:
  push:
    branches: [ "main" ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up the Docker builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Builds the image using your Dockerfile
      # (This is where npm install and pip install should happen, INSIDE the container)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Set to true if you want to push to a registry
